---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  namespace: nginx-fleet
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
